language: node_js
node_js:
  - "8"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli
  - yarn global add firebase-tools

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod --base-href https://vowelcorp.github.io/vowel/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  on:
    branch: master
